### ISSUE TITLE
NoSuchFieldError: AIR clicking on any item from a GUI

### ISSUE THREAD

**Issue by Eufranio** [codeHusky/HuskyUI-Plugin#16]
I installed Market (that uses HuskyUI), and clicking on any slot (having or no items) throw this exception.
Stacktrace:
```
> [03:31:07] [Server thread/ERROR] [Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=huskyui, name=HuskyUI, version=0.3.0, description=A framework for Inventory UI., source=/home/container/mods/HuskyUI-v0.3.0.jar}
java.lang.NoSuchFieldError: AIR
at com.codehusky.huskyui.states.Page.lambda$generatePageView$1(Page.java:229) ~[Page.class:?]
at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:52) ~[CustomInventoryListener.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:35) ~[CustomInventoryListener.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$33(PacketFunction.java:708) ~[PacketFunction.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:324) [PacketPhase.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:225) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:167) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2464]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2464]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2464]
at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3932) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by codeHusky** [comment]
I'll fix this.
