### ISSUE TITLE
Throwing some huge error

### ISSUE THREAD

**Issue by KhaozFrost** [codeHusky/HuskyUI-Plugin#19]
```
10.02 11:50:08 [Server] Server thread/INFO [STDOUT]: [com.codehusky.huskyui.HuskyUI:onItemClick:326]: Primary{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={net.minecraft.inventory.ContainerPlayer@43e1e0c3, EntityPlayerMP['LilMsJester'/46435, l='PixelmonWorld', x=1689.30, y=78.00, z=-633.85]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], cursorTransaction=Transaction{original=SpongeItemStackSnapshot{itemType=Item{Name=flint}, quantity=8}, default=SpongeItemStackSnapshot{itemType=ItemAir{Name=null}, quantity=0}, custom=null, valid=true}, entities=[EntityItem['item.item.flint'/193363, l='PixelmonWorld', x=1689.30, y=79.32, z=-633.85]], entitySnapshots=null, source=net.minecraft.inventory.ContainerPlayer@43e1e0c3, targetInventory=net.minecraft.inventory.ContainerPlayer@43e1e0c3, transactions=[]} 10.02 11:50:08 [Server] Server thread/ERROR [Sponge]: Could not pass ClickInventoryEvent$Drop$Outside$Primary$Impl to Plugin{id=huskyui, name=HuskyUI, version=0.5.1, description=A framework for Inventory UI., source=/mods/HuskyUI-v0.5.1-API7-8.jar} 10.02 11:50:08 [Server] INFO java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 10.02 11:50:08 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_151] 10.02 11:50:08 [Server] INFO at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_151] 10.02 11:50:08 [Server] INFO at com.codehusky.huskyui.HuskyUI.onItemClick(HuskyUI.java:328) ~[HuskyUI.class:?] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.listener.ClickInventoryEventListener_HuskyUI_onItemClick72.handle(Unknown Source) ~[?:?] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:315) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:367) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:201) [BasicInventoryPacketState.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:55) [BasicInventoryPacketState.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:232) [PhaseTracker.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:394) [PhaseContext.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkl000(SourceFile:539) [hv$1.class:?] 10.02 11:50:08 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?] 10.02 11:50:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151] 10.02 11:50:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151] 10.02 11:50:08 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?] 10.02 11:50:08 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.1.0-BETA-2844] 10.02 11:50:08 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zja000(MinecraftServer.java:4007) [MinecraftServer.class:?] 10.02 11:50:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?] 10.02 11:50:08 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 10.02 11:50:08 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?] 10.02 11:50:08 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?] 10.02 11:50:11 [Multicraft] Skipped 1 lines due to rate limit (30/s)
```

**Comment by codeHusky** [comment]
This isn't an error, it's just a printout.
