### ISSUE TITLE
bug when interacting with some inventories

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyUI-Plugin#21]
some error
```
[03:24:55] [Server thread/INFO] [STDOUT]: [com.codehusky.huskyui.HuskyUI:onItemClick:326]: Primary{cancelled=false, cause=Cause[Context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], Stack={net.minecraft.inventory.ContainerPlayer@1d604a51, EntityPlayerMP['Skeletonman0'/127, l='world', x=12639.51, y=156.02, z=-20947.17]}], context=Context["sponge:spawn_type"=SpongeSpawnType{id=sponge:dropped_item, name=DroppedItem}], cursorTransaction=Transaction{original=SpongeItemStackSnapshot{itemType=chisel:stonebrick, quantity=1}, default=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, custom=null, valid=true}, entities=[EntityItem['item.tile.chisel.stonebrick'/80986, l='world', x=12639.51, y=157.34, z=-20947.17]], entitySnapshots=null, source=net.minecraft.inventory.ContainerPlayer@1d604a51, targetInventory=net.minecraft.inventory.ContainerPlayer@1d604a51, transactions=[]}
>
[03:24:55] [Server thread/ERROR] [Sponge]: Could not pass ClickInventoryEvent$Drop$Outside$Primary$Impl to Plugin{id=huskyui, name=HuskyUI, version=0.5.1, description=A framework for Inventory UI., source=/home/container/mods/HuskyUI-v0.5.1-API7-8.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_161]
at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_161]
at com.codehusky.huskyui.HuskyUI.onItemClick(HuskyUI.java:328) ~[HuskyUI.class:?]
at org.spongepowered.common.event.listener.ClickInventoryEventListener_HuskyUI_onItemClick43.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:312) [SpongeModEventManager.class:1.12.2-2
611-7.1.0-BETA-2939]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:364) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:202) [BasicInventoryPacketState.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:55) [BasicInventoryPacketState.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:211) [PhaseTracker.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:392) [PhaseContext.class:1.12.2-2611-7.1.0-BETA-2939]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2939]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2939]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by codeHusky** [comment]
"fixed" in 0.5.2
